use anyhow::{Context, Result};
use apache_avro::{Schema as AvroSchemaDef, types::Value as AvroValue};
use arrow::array::*;
use arrow::datatypes::{DataType, Field, SchemaRef, TimeUnit};
use arrow::record_batch::RecordBatch;
use arrow_avro::schema::AvroSchema;
use std::convert::TryFrom;

// ---------------------------------------------------------------------------
// ArrowToAvroConverter
// ---------------------------------------------------------------------------

pub struct ArrowToAvroConverter {
    avro_schema: AvroSchemaDef,
    arrow_schema: SchemaRef,
    schema_json: String,
    schema_name: String,
    /// Per-field "inner" Avro schemas: for nullable fields the union is
    /// unwrapped so callers see the concrete type (e.g. `Schema::Long`),
    /// not `Schema::Union([Null, Long])`.
    ///
    /// Used by `arrow_value_to_avro_value` to dispatch the correct
    /// `AvroValue` variant when the arrow-avro crate omits logicalType
    /// annotations (e.g. emitting `{"type":"long"}` instead of
    /// `{"type":"long","logicalType":"timestamp-micros"}`).
    field_avro_schemas: Vec<AvroSchemaDef>,
    /// Whether each field's top-level Avro schema is a Union type.
    ///
    /// `arrow-avro` 58.x emits `["null", T]` Union schemas for some Arrow
    /// types (notably `Timestamp`) even when the Arrow field is non-nullable.
    /// This flag captures the *actual Avro structure* so that
    /// `arrow_value_to_avro_value` can correctly wrap values in
    /// `AvroValue::Union(1, …)` regardless of Arrow nullability.
    field_is_avro_union: Vec<bool>,
}

impl ArrowToAvroConverter {
    pub fn new(arrow_schema: SchemaRef) -> Result<Self> {
        let avro_schema_wrapper = AvroSchema::try_from(arrow_schema.as_ref())
            .map_err(|e| anyhow::anyhow!("Arrow to Avro conversion failed: {}", e))?;

        let avro_schema = AvroSchemaDef::parse_str(&avro_schema_wrapper.json_string)
            .context("Failed to parse the generated Avro JSON schema")?;

        let schema_name = match &avro_schema {
            AvroSchemaDef::Record(r) => r.name.name.clone(),
            _ => "record".to_string(),
        };

        // Extract the concrete (non-union) Avro schema for each field so
        // that value encoding can consult the real schema type rather than
        // assuming which logicalType the arrow-avro crate emitted.
        let field_avro_schemas = extract_field_inner_schemas(&avro_schema);

        // Track which fields have a Union Avro schema.  arrow-avro 58.x
        // wraps some types (notably Timestamp) in ["null", T] even when the
        // Arrow field is non-nullable, so we use Avro structure — not Arrow
        // nullability — to decide whether to emit AvroValue::Union wrappers.
        let field_is_avro_union: Vec<bool> = match &avro_schema {
            AvroSchemaDef::Record(r) => r
                .fields
                .iter()
                .map(|f| matches!(f.schema, AvroSchemaDef::Union(_)))
                .collect(),
            _ => vec![],
        };

        Ok(Self {
            avro_schema,
            arrow_schema,
            schema_json: avro_schema_wrapper.json_string,
            schema_name,
            field_avro_schemas,
            field_is_avro_union,
        })
    }

    pub fn schema_json(&self) -> &str {
        &self.schema_json
    }

    /// Return the Avro record name as derived from the converted schema.
    ///
    /// For Arrow schemas this is the `"name"` field of the top-level Avro
    /// record object (e.g. `"arrow_schema"` as generated by `arrow-avro`).
    /// Used by [`crate::schema_registry::SubjectNameStrategy`] to compute
    /// the Schema Registry subject for `RecordName` and `TopicRecordName`
    /// strategies.
    pub fn schema_name(&self) -> &str {
        &self.schema_name
    }

    pub fn convert_row(&self, batch: &RecordBatch, row_index: usize) -> Result<Vec<u8>> {
        if row_index >= batch.num_rows() {
            return Err(anyhow::anyhow!(
                "row_index {} out of bounds for batch with {} rows",
                row_index,
                batch.num_rows()
            ));
        }

        let mut fields = Vec::with_capacity(batch.num_columns());

        for (col_idx, field) in self.arrow_schema.fields().iter().enumerate() {
            let column = batch.column(col_idx);
            // Fall back to Schema::Null if field_avro_schemas is shorter than
            // the arrow schema (should never happen for well-formed inputs).
            let avro_field_schema = self
                .field_avro_schemas
                .get(col_idx)
                .unwrap_or(&AvroSchemaDef::Null);
            // Use the Avro-schema-derived union flag rather than Arrow's
            // is_nullable() — see field_is_avro_union doc for the rationale.
            let is_avro_union = self
                .field_is_avro_union
                .get(col_idx)
                .copied()
                .unwrap_or(false);
            let value = arrow_value_to_avro_value(
                column.as_ref(),
                field,
                avro_field_schema,
                row_index,
                is_avro_union,
            )?;
            fields.push((field.name().clone(), value));
        }

        let record = AvroValue::Record(fields);
        let buffer = apache_avro::to_avro_datum(&self.avro_schema, record)
            .context("Failed to encode pure Avro datum")?;

        Ok(buffer)
    }
}

// ---------------------------------------------------------------------------
// Per-field schema extraction
// ---------------------------------------------------------------------------

/// For each field of the top-level Avro Record schema, extract the
/// "concrete" inner schema — i.e. unwrap nullable unions so callers
/// see `Schema::Long` instead of `Schema::Union([Null, Long])`.
///
/// The resulting `Vec` is index-aligned with the Arrow schema's field list
/// (and with the Avro record's `fields` list, which should be identical in
/// ordering since we generated the Avro schema from Arrow).
fn extract_field_inner_schemas(avro_schema: &AvroSchemaDef) -> Vec<AvroSchemaDef> {
    match avro_schema {
        AvroSchemaDef::Record(r) => r
            .fields
            .iter()
            .map(|f| unwrap_nullable_schema(&f.schema))
            .collect(),
        _ => vec![],
    }
}

/// If `schema` is a two-variant nullable union (`["null", T]`), return a
/// clone of the non-null branch.  Otherwise return a clone of `schema` itself.
fn unwrap_nullable_schema(schema: &AvroSchemaDef) -> AvroSchemaDef {
    match schema {
        AvroSchemaDef::Union(u) => u
            .variants()
            .iter()
            .find(|s| !matches!(s, AvroSchemaDef::Null))
            .cloned()
            .unwrap_or(AvroSchemaDef::Null),
        s => s.clone(),
    }
}

// ---------------------------------------------------------------------------
// Arrow → Avro value conversion
// ---------------------------------------------------------------------------

/// Convert a single cell from an Arrow array to its Avro `Value`
/// representation.
///
/// # Parameters
/// - `array`            — The Arrow column array.
/// - `field`            — Arrow field descriptor (name, type, nullability).
/// - `avro_field_schema`— The *unwrapped* Avro schema for this field
///   (nullable unions already peeled to their inner type).  Used to
///   select the correct `AvroValue` variant for types whose Arrow→Avro
///   mapping is ambiguous (e.g. `Timestamp` may map to `Long`,
///   `TimestampMillis`, or `TimestampMicros` depending on what
///   `arrow-avro` emitted).
/// - `row_index`        — Row within the array.
fn arrow_value_to_avro_value(
    array: &dyn Array,
    field: &Field,
    avro_field_schema: &AvroSchemaDef,
    row_index: usize,
    is_avro_union: bool,
) -> Result<AvroValue> {
    // Use is_avro_union (derived from the actual Avro schema structure) rather
    // than field.is_nullable() (Arrow nullability) to decide Union wrapping.
    // arrow-avro 58.x emits ["null", T] Union schemas for Timestamp fields
    // even when the Arrow field is declared non-nullable, so Arrow nullability
    // alone is not a reliable signal for whether to produce AvroValue::Union.
    if array.is_null(row_index) {
        return if is_avro_union {
            Ok(AvroValue::Union(0, Box::new(AvroValue::Null)))
        } else {
            Ok(AvroValue::Null)
        };
    }

    let raw =
        match field.data_type() {
            // -------------------------------------------------------------------
            // String types
            // -------------------------------------------------------------------
            DataType::Utf8 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<StringArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected StringArray for field {}", field.name())
                    })?;
                AvroValue::String(arr.value(row_index).to_string())
            }
            DataType::LargeUtf8 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<LargeStringArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected LargeStringArray for field {}", field.name())
                    })?;
                AvroValue::String(arr.value(row_index).to_string())
            }

            // -------------------------------------------------------------------
            // Signed integer types
            // -------------------------------------------------------------------
            DataType::Int8 => {
                let arr = array.as_any().downcast_ref::<Int8Array>().ok_or_else(|| {
                    anyhow::anyhow!("Expected Int8Array for field {}", field.name())
                })?;
                AvroValue::Int(arr.value(row_index) as i32)
            }
            DataType::Int16 => {
                let arr = array.as_any().downcast_ref::<Int16Array>().ok_or_else(|| {
                    anyhow::anyhow!("Expected Int16Array for field {}", field.name())
                })?;
                AvroValue::Int(arr.value(row_index) as i32)
            }
            DataType::Int32 => {
                let arr = array.as_any().downcast_ref::<Int32Array>().ok_or_else(|| {
                    anyhow::anyhow!("Expected Int32Array for field {}", field.name())
                })?;
                AvroValue::Int(arr.value(row_index))
            }
            DataType::Int64 => {
                let arr = array.as_any().downcast_ref::<Int64Array>().ok_or_else(|| {
                    anyhow::anyhow!("Expected Int64Array for field {}", field.name())
                })?;
                AvroValue::Long(arr.value(row_index))
            }

            // -------------------------------------------------------------------
            // Unsigned integer types — mapped to Avro Long (no unsigned in Avro)
            // -------------------------------------------------------------------
            DataType::UInt8 => {
                let arr = array.as_any().downcast_ref::<UInt8Array>().ok_or_else(|| {
                    anyhow::anyhow!("Expected UInt8Array for field {}", field.name())
                })?;
                AvroValue::Long(arr.value(row_index) as i64)
            }
            DataType::UInt16 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<UInt16Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected UInt16Array for field {}", field.name())
                    })?;
                AvroValue::Long(arr.value(row_index) as i64)
            }
            DataType::UInt32 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<UInt32Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected UInt32Array for field {}", field.name())
                    })?;
                AvroValue::Long(arr.value(row_index) as i64)
            }
            DataType::UInt64 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<UInt64Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected UInt64Array for field {}", field.name())
                    })?;
                AvroValue::Long(arr.value(row_index) as i64)
            }

            // -------------------------------------------------------------------
            // Floating-point types
            // -------------------------------------------------------------------
            DataType::Float32 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<Float32Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected Float32Array for field {}", field.name())
                    })?;
                AvroValue::Float(arr.value(row_index))
            }
            DataType::Float64 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<Float64Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected Float64Array for field {}", field.name())
                    })?;
                AvroValue::Double(arr.value(row_index))
            }

            // -------------------------------------------------------------------
            // Boolean
            // -------------------------------------------------------------------
            DataType::Boolean => {
                let arr = array
                    .as_any()
                    .downcast_ref::<BooleanArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected BooleanArray for field {}", field.name())
                    })?;
                AvroValue::Boolean(arr.value(row_index))
            }

            // -------------------------------------------------------------------
            // Date32 → Avro `date` logical type (int, days since Unix epoch).
            //
            // arrow-avro reliably emits `{"type":"int","logicalType":"date"}` for
            // Date32, so apache-avro parses it as `Schema::Date` and we can
            // unconditionally use `AvroValue::Date`.
            // -------------------------------------------------------------------
            DataType::Date32 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<Date32Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected Date32Array for field {}", field.name())
                    })?;
                AvroValue::Date(arr.value(row_index))
            }

            // -------------------------------------------------------------------
            // Date64 — Arrow stores milliseconds since epoch.
            //
            // arrow-avro may emit different Avro types; dispatch on the actual
            // parsed schema to produce the matching AvroValue.
            //
            //   Schema::TimestampMillis → AvroValue::TimestampMillis(ms)
            //   Schema::TimestampMicros → AvroValue::TimestampMicros(ms × 1000)
            //   Schema::Date            → AvroValue::Date(ms / 86_400_000)
            //   Schema::Long (fallback) → AvroValue::Long(ms)
            // -------------------------------------------------------------------
            DataType::Date64 => {
                let arr = array
                    .as_any()
                    .downcast_ref::<Date64Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected Date64Array for field {}", field.name())
                    })?;
                let millis = arr.value(row_index);
                match avro_field_schema {
                    AvroSchemaDef::TimestampMillis => AvroValue::TimestampMillis(millis),
                    AvroSchemaDef::TimestampMicros => {
                        AvroValue::TimestampMicros(millis.saturating_mul(1_000))
                    }
                    AvroSchemaDef::Date => AvroValue::Date((millis / 86_400_000) as i32),
                    _ => AvroValue::Long(millis),
                }
            }

            // -------------------------------------------------------------------
            // Timestamp — all four Arrow time-units supported.
            //
            // arrow-avro may or may not emit logicalType annotations, so we
            // dispatch on the *actual* Avro schema rather than assuming it:
            //
            //   Schema::TimestampMillis → AvroValue::TimestampMillis(value_in_ms)
            //   Schema::TimestampMicros → AvroValue::TimestampMicros(value_in_µs)
            //   Schema::Long (fallback) → AvroValue::Long(native Arrow value)
            //
            // For the Long fallback, we preserve the native Arrow resolution
            // (seconds / ms / µs / ns) unchanged so the producer and any
            // schema-aware consumer can agree on units via out-of-band convention.
            //
            // Sub-microsecond precision is truncated when upscaling nanoseconds
            // to microseconds (÷ 1 000).
            // -------------------------------------------------------------------
            DataType::Timestamp(unit, _) => {
                encode_timestamp(array, field, unit, avro_field_schema, row_index)?
            }

            // -------------------------------------------------------------------
            // Binary types → Avro `bytes`
            //
            // All three Arrow binary variants produce `AvroValue::Bytes`.
            // FixedSizeBinary length is not re-validated here; the Avro schema
            // produced by arrow-avro uses variable-length `bytes`.
            // -------------------------------------------------------------------
            DataType::Binary => {
                let arr = array
                    .as_any()
                    .downcast_ref::<BinaryArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected BinaryArray for field {}", field.name())
                    })?;
                AvroValue::Bytes(arr.value(row_index).to_vec())
            }
            DataType::LargeBinary => {
                let arr = array
                    .as_any()
                    .downcast_ref::<LargeBinaryArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected LargeBinaryArray for field {}", field.name())
                    })?;
                AvroValue::Bytes(arr.value(row_index).to_vec())
            }
            DataType::FixedSizeBinary(_) => {
                let arr = array
                    .as_any()
                    .downcast_ref::<FixedSizeBinaryArray>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected FixedSizeBinaryArray for field {}", field.name())
                    })?;
                AvroValue::Bytes(arr.value(row_index).to_vec())
            }

            // -------------------------------------------------------------------
            // Decimal128 → Avro `decimal` logical type
            //
            // Arrow Decimal128 stores the unscaled i128 integer value.  Avro
            // `decimal` encodes the unscaled value as big-endian two's-complement
            // bytes.  We use a minimal encoding (fewest bytes that still preserve
            // the value and sign) to keep payload sizes small.
            // -------------------------------------------------------------------
            DataType::Decimal128(_precision, _scale) => {
                let arr = array
                    .as_any()
                    .downcast_ref::<Decimal128Array>()
                    .ok_or_else(|| {
                        anyhow::anyhow!("Expected Decimal128Array for field {}", field.name())
                    })?;
                let unscaled: i128 = arr.value(row_index);
                let be_bytes = i128_to_avro_bytes(unscaled);
                AvroValue::Decimal(apache_avro::Decimal::from(be_bytes))
            }

            // -------------------------------------------------------------------
            // Unsupported — surface a structured error so the sink can map it to
            // SinkError::UnsupportedType / UnsupportedTypeError in Python.
            // -------------------------------------------------------------------
            dt => {
                return Err(anyhow::anyhow!(
                    "Unsupported Arrow data type {:?} for field {} in Avro conversion",
                    dt,
                    field.name()
                ));
            }
        };

    // Wrap in a Union when the Avro field schema is a Union type:
    //   Union(0, Null)  — null branch (handled at the top of this function)
    //   Union(1, value) — value branch
    if is_avro_union {
        Ok(AvroValue::Union(1, Box::new(raw)))
    } else {
        Ok(raw)
    }
}

// ---------------------------------------------------------------------------
// Timestamp encoding — extracted to keep the match arm readable
// ---------------------------------------------------------------------------

/// Encode a single Timestamp cell as the `AvroValue` that matches the
/// *actual* Avro field schema (which may or may not carry a logicalType).
///
/// # Why this function exists
/// `arrow-avro` 58.x does not always emit logicalType annotations for
/// Timestamp Arrow types.  Concretely, it can generate `{"type":"long"}`
/// instead of `{"type":"long","logicalType":"timestamp-micros"}`.  When
/// apache-avro parses the schema as `Schema::Long`, passing
/// `AvroValue::TimestampMicros` fails validation ("Value does not match
/// schema").  We therefore read the *actual* parsed Avro schema to decide
/// which `AvroValue` variant to produce.
#[inline]
fn encode_timestamp(
    array: &dyn Array,
    field: &Field,
    unit: &TimeUnit,
    avro_field_schema: &AvroSchemaDef,
    row_index: usize,
) -> Result<AvroValue> {
    // Step 1: extract the raw i64 value at the Arrow native resolution.
    let raw: i64 = match unit {
        TimeUnit::Second => array
            .as_any()
            .downcast_ref::<TimestampSecondArray>()
            .ok_or_else(|| {
                anyhow::anyhow!("Expected TimestampSecondArray for field {}", field.name())
            })?
            .value(row_index),
        TimeUnit::Millisecond => array
            .as_any()
            .downcast_ref::<TimestampMillisecondArray>()
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "Expected TimestampMillisecondArray for field {}",
                    field.name()
                )
            })?
            .value(row_index),
        TimeUnit::Microsecond => array
            .as_any()
            .downcast_ref::<TimestampMicrosecondArray>()
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "Expected TimestampMicrosecondArray for field {}",
                    field.name()
                )
            })?
            .value(row_index),
        TimeUnit::Nanosecond => array
            .as_any()
            .downcast_ref::<TimestampNanosecondArray>()
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "Expected TimestampNanosecondArray for field {}",
                    field.name()
                )
            })?
            .value(row_index),
    };

    // Step 2: convert `raw` to the resolution expected by the Avro schema.
    //
    // Conversion table (rows = Arrow unit, columns = target Avro type):
    //
    //   Arrow unit  │ TimestampMillis │ TimestampMicros │ Long (fallback)
    //   ────────────┼─────────────────┼─────────────────┼─────────────────
    //   Second      │ raw × 1 000     │ raw × 1 000 000 │ raw (seconds)
    //   Millisecond │ raw             │ raw × 1 000     │ raw (ms)
    //   Microsecond │ raw / 1 000     │ raw             │ raw (µs)
    //   Nanosecond  │ raw / 1 000 000 │ raw / 1 000     │ raw (ns)
    //
    // Sub-unit precision is truncated (integer division), not rounded.
    Ok(match avro_field_schema {
        AvroSchemaDef::TimestampMillis | AvroSchemaDef::LocalTimestampMillis => {
            let ms = match unit {
                TimeUnit::Second => raw.saturating_mul(1_000),
                TimeUnit::Millisecond => raw,
                TimeUnit::Microsecond => raw / 1_000,
                TimeUnit::Nanosecond => raw / 1_000_000,
            };
            AvroValue::TimestampMillis(ms)
        }
        AvroSchemaDef::TimestampMicros | AvroSchemaDef::LocalTimestampMicros => {
            let us = match unit {
                TimeUnit::Second => raw.saturating_mul(1_000_000),
                TimeUnit::Millisecond => raw.saturating_mul(1_000),
                TimeUnit::Microsecond => raw,
                TimeUnit::Nanosecond => raw / 1_000,
            };
            AvroValue::TimestampMicros(us)
        }
        // Fallback: the Avro schema carries no logicalType (Schema::Long).
        // Preserve the value at its native Arrow resolution so schema-aware
        // consumers can apply their own interpretation.
        _ => AvroValue::Long(raw),
    })
}

// ---------------------------------------------------------------------------
// Decimal128 helper
// ---------------------------------------------------------------------------

/// Convert an `i128` to the minimal big-endian two's-complement byte slice
/// required by the Avro `decimal` logical type.
///
/// "Minimal" means the leading byte is the smallest prefix that still
/// unambiguously represents the sign:
/// - Positive: no leading `0x00` bytes, unless the next byte would have its
///   high bit set (which would misrepresent it as negative).
/// - Negative: no leading `0xFF` bytes, unless the next byte has its high bit
///   clear (which would misrepresent it as positive).
///
/// Examples:
/// ```text
///  0        → [0x00]
///  1        → [0x01]
/// -1        → [0xFF]
///  127      → [0x7F]
///  128      → [0x00, 0x80]   ← needs leading 0x00 to stay positive
/// -128      → [0x80]
/// -129      → [0xFF, 0x7F]
/// ```
fn i128_to_avro_bytes(value: i128) -> Vec<u8> {
    let be = value.to_be_bytes(); // 16-byte big-endian two's complement
    let mut start = 0usize;

    if value >= 0 {
        while start < 15 && be[start] == 0x00 && (be[start + 1] & 0x80) == 0 {
            start += 1;
        }
    } else {
        while start < 15 && be[start] == 0xFF && (be[start + 1] & 0x80) != 0 {
            start += 1;
        }
    }

    be[start..].to_vec()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use arrow::datatypes::{Field, Schema};
    use std::sync::Arc;

    // -----------------------------------------------------------------------
    // Diagnostic: print actual Avro JSON produced by arrow-avro for Timestamps
    // Run with: cargo test --lib -- converter::tests::diag_timestamp_schema --nocapture
    // -----------------------------------------------------------------------

    #[test]
    fn diag_timestamp_schema_json() {
        for (name, dt) in [
            ("ts_s", DataType::Timestamp(TimeUnit::Second, None)),
            ("ts_ms", DataType::Timestamp(TimeUnit::Millisecond, None)),
            ("ts_us", DataType::Timestamp(TimeUnit::Microsecond, None)),
            ("ts_ns", DataType::Timestamp(TimeUnit::Nanosecond, None)),
        ] {
            // non-nullable
            let schema = Arc::new(Schema::new(vec![Field::new(name, dt.clone(), false)]));
            let wrapper = arrow_avro::schema::AvroSchema::try_from(schema.as_ref()).unwrap();
            eprintln!("[non-nullable {}] JSON: {}", name, wrapper.json_string);

            let avro = apache_avro::Schema::parse_str(&wrapper.json_string).unwrap();
            if let apache_avro::Schema::Record(r) = &avro {
                for f in &r.fields {
                    eprintln!(
                        "  field '{}' schema variant: {:?}  is_union={}",
                        f.name,
                        std::mem::discriminant(&f.schema),
                        matches!(f.schema, apache_avro::Schema::Union(_)),
                    );
                }
            }

            // nullable
            let schema2 = Arc::new(Schema::new(vec![Field::new(name, dt.clone(), true)]));
            let wrapper2 = arrow_avro::schema::AvroSchema::try_from(schema2.as_ref()).unwrap();
            eprintln!("[nullable {}] JSON: {}", name, wrapper2.json_string);

            let avro2 = apache_avro::Schema::parse_str(&wrapper2.json_string).unwrap();
            if let apache_avro::Schema::Record(r) = &avro2 {
                for f in &r.fields {
                    eprintln!(
                        "  field '{}' schema variant: {:?}  is_union={}",
                        f.name,
                        std::mem::discriminant(&f.schema),
                        matches!(f.schema, apache_avro::Schema::Union(_)),
                    );
                }
            }
        }
    }
    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    fn make(
        schema: Arc<Schema>,
        arrays: Vec<Arc<dyn Array>>,
    ) -> (RecordBatch, ArrowToAvroConverter) {
        let batch = RecordBatch::try_new(schema.clone(), arrays).expect("valid batch");
        let conv = ArrowToAvroConverter::new(schema).expect("valid converter");
        (batch, conv)
    }

    fn single_field(name: &str, dt: DataType, nullable: bool) -> Arc<Schema> {
        Arc::new(Schema::new(vec![Field::new(name, dt, nullable)]))
    }

    // -----------------------------------------------------------------------
    // i128_to_avro_bytes
    // -----------------------------------------------------------------------

    #[test]
    fn avro_bytes_zero_is_single_zero_byte() {
        assert_eq!(i128_to_avro_bytes(0), vec![0x00]);
    }

    #[test]
    fn avro_bytes_one() {
        assert_eq!(i128_to_avro_bytes(1), vec![0x01]);
    }

    #[test]
    fn avro_bytes_minus_one_is_single_ff_byte() {
        assert_eq!(i128_to_avro_bytes(-1), vec![0xFF]);
    }

    #[test]
    fn avro_bytes_127_fits_in_one_byte() {
        assert_eq!(i128_to_avro_bytes(127), vec![0x7F]);
    }

    #[test]
    fn avro_bytes_128_needs_leading_zero_to_stay_positive() {
        assert_eq!(i128_to_avro_bytes(128), vec![0x00, 0x80]);
    }

    #[test]
    fn avro_bytes_minus_128_fits_in_one_byte() {
        assert_eq!(i128_to_avro_bytes(-128), vec![0x80]);
    }

    #[test]
    fn avro_bytes_minus_129_two_bytes() {
        assert_eq!(i128_to_avro_bytes(-129), vec![0xFF, 0x7F]);
    }

    #[test]
    fn avro_bytes_roundtrip_sign_is_preserved() {
        for val in [
            0_i128,
            1,
            -1,
            127,
            128,
            -128,
            -129,
            i64::MAX as i128,
            i64::MIN as i128,
        ] {
            let bytes = i128_to_avro_bytes(val);
            let sign_byte = if (bytes[0] & 0x80) != 0 {
                0xFF_u8
            } else {
                0x00
            };
            let mut buf = [sign_byte; 16];
            let offset = 16 - bytes.len();
            buf[offset..].copy_from_slice(&bytes);
            let reconstructed = i128::from_be_bytes(buf);
            assert_eq!(
                reconstructed, val,
                "roundtrip failed for {val}: bytes={bytes:?}"
            );
        }
    }

    // -----------------------------------------------------------------------
    // Date / Binary / basic types
    // -----------------------------------------------------------------------

    #[test]
    fn converter_date32_serialises() {
        let schema = single_field("d", DataType::Date32, false);
        let arr = Date32Array::from(vec![19000_i32]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        let bytes = conv.convert_row(&batch, 0).expect("Date32 must serialise");
        assert!(!bytes.is_empty());
    }

    #[test]
    fn converter_binary_serialises() {
        let schema = single_field("b", DataType::Binary, false);
        let arr = BinaryArray::from_vec(vec![b"hello".as_slice()]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        let bytes = conv.convert_row(&batch, 0).expect("Binary must serialise");
        assert!(!bytes.is_empty());
    }

    #[test]
    fn converter_fixed_size_binary_serialises() {
        let schema = single_field("fsb", DataType::FixedSizeBinary(4), false);
        let arr =
            FixedSizeBinaryArray::try_from_iter(vec![vec![0xDE_u8, 0xAD, 0xBE, 0xEF]].into_iter())
                .expect("valid FixedSizeBinary");
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        let bytes = conv
            .convert_row(&batch, 0)
            .expect("FixedSizeBinary must serialise");
        assert!(!bytes.is_empty());
    }

    // -----------------------------------------------------------------------
    // Timestamp — all four time-units.
    //
    // We do not assert on the exact AvroValue variant because that depends on
    // what logicalType arrow-avro emits; we only assert that serialisation
    // succeeds and produces a non-empty payload.
    // -----------------------------------------------------------------------

    #[test]
    fn converter_timestamp_second_serialises() {
        let dt = DataType::Timestamp(TimeUnit::Second, None);
        let schema = single_field("ts_s", dt, false);
        let arr = TimestampSecondArray::from(vec![1_700_000_000_i64]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        conv.convert_row(&batch, 0)
            .expect("Timestamp(s) must serialise");
    }

    #[test]
    fn converter_timestamp_millisecond_serialises() {
        let dt = DataType::Timestamp(TimeUnit::Millisecond, None);
        let schema = single_field("ts_ms", dt, false);
        let arr = TimestampMillisecondArray::from(vec![1_700_000_000_000_i64]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        conv.convert_row(&batch, 0)
            .expect("Timestamp(ms) must serialise");
    }

    #[test]
    fn converter_timestamp_microsecond_serialises() {
        let dt = DataType::Timestamp(TimeUnit::Microsecond, None);
        let schema = single_field("ts_us", dt, false);
        let arr = TimestampMicrosecondArray::from(vec![1_700_000_000_000_000_i64]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        conv.convert_row(&batch, 0)
            .expect("Timestamp(µs) must serialise");
    }

    #[test]
    fn converter_timestamp_nanosecond_serialises() {
        let dt = DataType::Timestamp(TimeUnit::Nanosecond, None);
        let schema = single_field("ts_ns", dt, false);
        let arr = TimestampNanosecondArray::from(vec![1_700_000_000_000_000_000_i64]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        conv.convert_row(&batch, 0)
            .expect("Timestamp(ns) must serialise");
    }

    #[test]
    fn converter_timestamp_nullable_with_null_serialises() {
        let dt = DataType::Timestamp(TimeUnit::Microsecond, None);
        let schema = single_field("ts_null", dt, true);
        let arr: TimestampMicrosecondArray = vec![None].into_iter().collect();
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        conv.convert_row(&batch, 0)
            .expect("nullable null Timestamp must serialise");
    }

    // -----------------------------------------------------------------------
    // Timestamp encode_timestamp unit helper — schema-dispatch logic
    // -----------------------------------------------------------------------

    /// Build a fake AvroSchemaDef for testing encode_timestamp dispatch.
    fn fake_field(name: &str) -> Field {
        Field::new(
            name,
            DataType::Timestamp(TimeUnit::Microsecond, None),
            false,
        )
    }

    #[test]
    fn encode_timestamp_long_fallback_preserves_native_value() {
        // When the Avro schema is Schema::Long (no logicalType), the raw
        // microsecond value should be returned as AvroValue::Long unchanged.
        let field = fake_field("ts");
        let arr = TimestampMicrosecondArray::from(vec![42_000_i64]);
        let batch = RecordBatch::try_new(
            Arc::new(Schema::new(vec![field.clone()])),
            vec![Arc::new(arr)],
        )
        .unwrap();

        let result = encode_timestamp(
            batch.column(0).as_ref(),
            &field,
            &TimeUnit::Microsecond,
            &AvroSchemaDef::Long,
            0,
        )
        .unwrap();

        assert!(
            matches!(result, AvroValue::Long(42_000)),
            "expected Long(42000), got {result:?}"
        );
    }

    #[test]
    fn encode_timestamp_millis_schema_converts_seconds_correctly() {
        let field = fake_field("ts");
        let arr = TimestampSecondArray::from(vec![1_000_i64]);
        let batch = RecordBatch::try_new(
            Arc::new(Schema::new(vec![Field::new(
                "ts",
                DataType::Timestamp(TimeUnit::Second, None),
                false,
            )])),
            vec![Arc::new(arr)],
        )
        .unwrap();

        let result = encode_timestamp(
            batch.column(0).as_ref(),
            &field,
            &TimeUnit::Second,
            &AvroSchemaDef::TimestampMillis,
            0,
        )
        .unwrap();

        assert!(
            matches!(result, AvroValue::TimestampMillis(1_000_000)),
            "1000s → 1_000_000ms expected, got {result:?}"
        );
    }

    #[test]
    fn encode_timestamp_micros_schema_converts_nanoseconds_correctly() {
        let field = fake_field("ts");
        let arr = TimestampNanosecondArray::from(vec![5_000_i64]);
        let batch = RecordBatch::try_new(
            Arc::new(Schema::new(vec![Field::new(
                "ts",
                DataType::Timestamp(TimeUnit::Nanosecond, None),
                false,
            )])),
            vec![Arc::new(arr)],
        )
        .unwrap();

        let result = encode_timestamp(
            batch.column(0).as_ref(),
            &field,
            &TimeUnit::Nanosecond,
            &AvroSchemaDef::TimestampMicros,
            0,
        )
        .unwrap();

        assert!(
            matches!(result, AvroValue::TimestampMicros(5)),
            "5000ns → 5µs expected, got {result:?}"
        );
    }

    // -----------------------------------------------------------------------
    // Nullable fields
    // -----------------------------------------------------------------------

    #[test]
    fn converter_handles_nullable_string_null_row() {
        let schema = single_field("s", DataType::Utf8, true);
        let arr = StringArray::from(vec![None::<&str>, Some("hello")]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        // row 0: null
        conv.convert_row(&batch, 0)
            .expect("null row must serialise");
        // row 1: non-null
        conv.convert_row(&batch, 1)
            .expect("non-null row must serialise");
    }

    // -----------------------------------------------------------------------
    // Out-of-bounds row
    // -----------------------------------------------------------------------

    #[test]
    fn converter_out_of_bounds_row_returns_error() {
        let schema = single_field("x", DataType::Int32, false);
        let arr = Int32Array::from(vec![1_i32]);
        let (batch, conv) = make(schema, vec![Arc::new(arr)]);
        let err = conv.convert_row(&batch, 1).unwrap_err();
        assert!(
            err.to_string().contains("out of bounds") || err.to_string().contains("row_index"),
            "error should mention bounds: {err}"
        );
    }

    // -----------------------------------------------------------------------
    // schema_json and schema_name
    // -----------------------------------------------------------------------

    #[test]
    fn converter_schema_json_is_valid_avro_object() {
        let schema = single_field("price", DataType::Float64, false);
        let arr = Float64Array::from(vec![1.0_f64]);
        let (_, conv) = make(schema, vec![Arc::new(arr)]);
        let json = conv.schema_json();
        assert!(
            json.trim_start().starts_with('{'),
            "must be JSON object: {json}"
        );
        assert!(
            json.contains("\"record\""),
            "must declare type=record: {json}"
        );
        assert!(
            json.contains("\"fields\""),
            "must have fields array: {json}"
        );
    }

    #[test]
    fn converter_schema_name_is_non_empty_and_stable() {
        let schema = single_field("v", DataType::Boolean, false);
        let arr = BooleanArray::from(vec![true]);
        let (_, conv) = make(schema, vec![Arc::new(arr)]);
        let name = conv.schema_name();
        assert!(!name.is_empty(), "schema_name must not be empty");
        assert_eq!(name, conv.schema_name(), "schema_name must be stable");
    }
}
