use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

use schema_registry_converter::blocking::schema_registry;
use schema_registry_converter::blocking::schema_registry::SrSettings;
use schema_registry_converter::schema_registry_common::{SchemaType, SuppliedSchema};

// ---------------------------------------------------------------------------
// Subject naming strategy
// ---------------------------------------------------------------------------

/// Controls how the Schema Registry subject name is derived from a topic and
/// an Avro record name.
///
/// Matches the three strategies defined in the Confluent Schema Registry
/// client specification:
///
/// | Variant            | Subject pattern              | Materialize compatible |
/// |--------------------|------------------------------|------------------------|
/// | `TopicName`        | `{topic}-value`              | ✓ (default)            |
/// | `RecordName`       | `{avro_record_name}`         | only if subject exists |
/// | `TopicRecordName`  | `{topic}-{avro_record_name}` | only if subject exists |
///
/// **Default is `TopicName`**, which is what Confluent Kafka, Redpanda, and
/// Materialize's `VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY` all
/// expect out of the box.
#[derive(Clone, Debug, Default)]
pub enum SubjectNameStrategy {
    /// `{topic}-value` — Confluent default.
    ///
    /// Use this unless you have an explicit reason to deviate; it is the only
    /// strategy directly compatible with Materialize's default source
    /// definition without extra configuration.
    #[default]
    TopicName,

    /// `{avro_record_name}` — schema-centric naming.
    ///
    /// The subject is derived solely from the Avro record's `name` field as
    /// generated by the Arrow → Avro schema converter.  Different topics that
    /// share the same Arrow schema will therefore share a single subject.
    RecordName,

    /// `{topic}-{avro_record_name}` — fully-qualified naming.
    ///
    /// Combines topic and record name, giving each (topic, schema) pair its
    /// own subject.
    TopicRecordName,
}

impl SubjectNameStrategy {
    /// Parse a strategy from a lowercase string identifier.
    ///
    /// Valid values: `"topic_name"`, `"record_name"`, `"topic_record_name"`.
    ///
    /// Returns `Err` with a descriptive message on unrecognised input so the
    /// caller can surface it as a `ConfigError` / `ValueError`.
    pub fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "topic_name" => Ok(Self::TopicName),
            "record_name" => Ok(Self::RecordName),
            "topic_record_name" => Ok(Self::TopicRecordName),
            other => Err(format!(
                "unknown subject_name_strategy '{other}'; \
                 valid values: topic_name, record_name, topic_record_name"
            )),
        }
    }

    /// Compute the subject name given a topic and the Avro record name.
    ///
    /// `record_name` is the `"name"` field of the top-level Avro record schema
    /// as produced by the `arrow-avro` converter (typically `"arrow_schema"`
    /// unless overridden).
    pub fn subject(&self, topic: &str, record_name: &str) -> String {
        match self {
            Self::TopicName => format!("{topic}-value"),
            Self::RecordName => record_name.to_string(),
            Self::TopicRecordName => format!("{topic}-{record_name}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Schema Registry client
// ---------------------------------------------------------------------------

/// Thin, caching wrapper around the blocking Confluent Schema Registry client.
///
/// # Caching
/// Schema IDs are cached in memory keyed by `"{subject}::{schema_json}"`.
/// Once a `(subject, schema)` pair has been registered, subsequent calls for
/// the same pair skip the network round-trip entirely.
///
/// # Thread safety
/// `SrClient` is `Clone` and all mutable state is behind `Arc<Mutex<_>>` or
/// `Arc<AtomicU64>`, making it safe to share across threads.
#[derive(Clone)]
pub struct SrClient {
    settings: Arc<SrSettings>,
    /// In-process cache: `"{subject}::{schema_json}"` → `schema_id`.
    cache: Arc<Mutex<HashMap<String, u32>>>,
    /// Strategy used to derive the subject name from topic + record name.
    pub strategy: SubjectNameStrategy,
    /// Number of schema lookups served from the in-process cache.
    cache_hits: Arc<AtomicU64>,
    /// Number of schema lookups that required a network round-trip.
    cache_misses: Arc<AtomicU64>,
}

impl SrClient {
    /// Create a new `SrClient`.
    ///
    /// # Arguments
    /// * `schema_registry_url` — Base URL of the Schema Registry
    ///   (e.g. `"http://localhost:8081"`).  No trailing slash required.
    /// * `strategy` — Subject naming strategy; defaults to `TopicName`.
    pub fn new(schema_registry_url: String, strategy: SubjectNameStrategy) -> anyhow::Result<Self> {
        let settings = SrSettings::new(schema_registry_url);
        Ok(Self {
            settings: Arc::new(settings),
            cache: Arc::new(Mutex::new(HashMap::new())),
            strategy,
            cache_hits: Arc::new(AtomicU64::new(0)),
            cache_misses: Arc::new(AtomicU64::new(0)),
        })
    }

    /// Return a `(hits, misses)` snapshot of the Schema Registry cache counters.
    ///
    /// Both values are monotonically increasing since the client was created.
    /// Used by [`ArrowKafkaSink::stats()`](crate::sink::ArrowKafkaSink::stats)
    /// to populate the `sr_cache_hits` and `sr_cache_misses` fields of
    /// [`SinkStats`](crate::stats::SinkStats).
    pub fn cache_stats(&self) -> (u64, u64) {
        (
            self.cache_hits.load(Ordering::Relaxed),
            self.cache_misses.load(Ordering::Relaxed),
        )
    }

    /// Compute the subject name for the given topic and Avro record name
    /// using the configured `SubjectNameStrategy`.
    pub fn subject(&self, topic: &str, record_name: &str) -> String {
        self.strategy.subject(topic, record_name)
    }

    /// Wrap a raw Avro datum in the Confluent wire format.
    ///
    /// Wire format: `[magic_byte=0x00][schema_id: 4 bytes big-endian][avro_datum]`
    ///
    /// This is the format expected by Confluent-compatible consumers and by
    /// Materialize's `VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY`.
    pub fn confluent_frame(schema_id: u32, avro_payload: &[u8]) -> Vec<u8> {
        let mut out = Vec::with_capacity(1 + 4 + avro_payload.len());
        out.push(0u8); // magic byte
        out.extend_from_slice(&schema_id.to_be_bytes());
        out.extend_from_slice(avro_payload);
        out
    }

    /// Return the cached schema ID for `(topic, schema_json)`, registering
    /// the schema with the Schema Registry if this is the first time this
    /// combination has been seen.
    ///
    /// The subject is computed from `topic` and `record_name` according to
    /// the configured [`SubjectNameStrategy`].
    ///
    /// # Arguments
    /// * `topic`       — Destination Kafka topic name.
    /// * `schema_json` — Avro schema JSON string (used both as the payload
    ///   sent to the registry and as the cache key discriminator).
    /// * `record_name` — The Avro record's `"name"` field, used by
    ///   `RecordName` and `TopicRecordName` strategies.
    ///
    /// # Errors
    /// Returns an `anyhow::Error` whose message begins with
    /// `"schema registry error [subject=...]:"` on network or HTTP errors.
    /// The caller (`sink.rs`) is responsible for mapping this to
    /// `SinkError::SchemaRegistry`.
    pub fn get_or_register_schema_id(
        &self,
        topic: &str,
        schema_json: &str,
        record_name: &str,
    ) -> anyhow::Result<u32> {
        let subject = self.subject(topic, record_name);
        // Cache key includes both subject and schema so we correctly handle
        // the case where the same topic evolves its schema over time.
        let cache_key = format!("{subject}::{schema_json}");

        // Fast path: cache hit.
        if let Some(id) = self
            .cache
            .lock()
            .ok()
            .and_then(|m| m.get(&cache_key).copied())
        {
            self.cache_hits.fetch_add(1, Ordering::Relaxed);
            return Ok(id);
        }

        // Slow path: register (or look up) the schema.
        self.cache_misses.fetch_add(1, Ordering::Relaxed);
        let supplied = SuppliedSchema {
            name: None,
            schema_type: SchemaType::Avro,
            schema: schema_json.to_string(),
            references: vec![],
            properties: None,
            tags: None,
        };

        let registered = schema_registry::post_schema(&self.settings, subject.clone(), supplied)
            .map_err(|e| anyhow::anyhow!("schema registry error [subject={subject}]: {e}"))?;

        let schema_id = registered.id;
        if let Ok(mut m) = self.cache.lock() {
            m.insert(cache_key, schema_id);
        }

        Ok(schema_id)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn topic_name_strategy() {
        let s = SubjectNameStrategy::TopicName;
        assert_eq!(s.subject("my_topic", "arrow_schema"), "my_topic-value");
    }

    #[test]
    fn record_name_strategy() {
        let s = SubjectNameStrategy::RecordName;
        assert_eq!(s.subject("my_topic", "TradeRecord"), "TradeRecord");
    }

    #[test]
    fn topic_record_name_strategy() {
        let s = SubjectNameStrategy::TopicRecordName;
        assert_eq!(s.subject("my_topic", "TradeRecord"), "my_topic-TradeRecord");
    }

    #[test]
    fn from_str_valid() {
        assert!(matches!(
            SubjectNameStrategy::from_str("topic_name"),
            Ok(SubjectNameStrategy::TopicName)
        ));
        assert!(matches!(
            SubjectNameStrategy::from_str("record_name"),
            Ok(SubjectNameStrategy::RecordName)
        ));
        assert!(matches!(
            SubjectNameStrategy::from_str("topic_record_name"),
            Ok(SubjectNameStrategy::TopicRecordName)
        ));
    }

    #[test]
    fn from_str_invalid() {
        let err = SubjectNameStrategy::from_str("bad_value").unwrap_err();
        assert!(err.contains("bad_value"));
        assert!(err.contains("topic_name"));
    }
}
